const data = [
	{ status: 'OK', msg: 'Went out to hunt girls' },
	{ status: 'OK', msg: 'starting the SIMP server' },
	{ status: 'OK', msg: 'Lookings for kawai chicks' },
	{ status: 'OK', msg: 'Getting attrackted at first sight' },
	{ status: 'OK', msg: 'Seeing another cute chick' },
	{ status: 'OK', msg: 'Fallign for her too' },
	{ status: 'OK', msg: 'Dreaming about getting married with her' },
	{ status: 'OK', msg: 'having 11 Babyes' },
	{ status: 'OK', msg: 'She looked at me ' },
	{ status: 'OK', msg: 'i smilled' },
	{ status: 'OK', msg: 'she smilled' },
	{ status: 'OK', msg: 'went to ask her number ' },
	{ status: 'Failed', msg: 'she said i looked like her brother' },
	{ status: 'OK', msg: 'Went out to hunt girls' },
	{ status: 'OK', msg: 'starting the SIMP server' },
	{ status: 'OK', msg: 'Lookings for kawai chicks' },
	{ status: 'OK', msg: 'Getting attrackted at first sight' },
	{ status: 'OK', msg: 'Seeing another cute chick' },
	{ status: 'OK', msg: 'Fallign for her too' },
	{ status: 'OK', msg: 'Dreaming about getting married with her' },
	{ status: 'OK', msg: 'having 11 Babyes' },
	{ status: 'OK', msg: 'She looked at me ' },
	{ status: 'OK', msg: 'i smilled' },
	{ status: 'OK', msg: 'she smilled' },
	{ status: 'OK', msg: 'went to ask her number ' },
	{ status: 'Failed', msg: 'she said i looked like her brother' },
	{ status: 'OK', msg: 'Went out to hunt girls' },
	{ status: 'OK', msg: 'starting the SIMP server' },
	{ status: 'OK', msg: 'Lookings for kawai chicks' },
	{ status: 'OK', msg: 'Getting attrackted at first sight' },
	{ status: 'OK', msg: 'Seeing another cute chick' },
	{ status: 'OK', msg: 'Fallign for her too' },
	{ status: 'OK', msg: 'Dreaming about getting married with her' },
	{ status: 'OK', msg: 'having 11 Babyes' },
	{ status: 'OK', msg: 'She looked at me ' },
	{ status: 'OK', msg: 'i smilled' },
	{ status: 'OK', msg: 'she smilled' },
	{ status: 'OK', msg: 'went to ask her number ' },
	{ status: 'Failed', msg: 'she said i looked like her brother' },
	{ status: 'OK', msg: 'Went out to hunt girls' },
	{ status: 'OK', msg: 'starting the SIMP server' },
	{ status: 'OK', msg: 'Lookings for kawai chicks' },
	{ status: 'OK', msg: 'Getting attrackted at first sight' },
	{ status: 'OK', msg: 'Seeing another cute chick' },
	{ status: 'OK', msg: 'Fallign for her too' },
	{ status: 'OK', msg: 'Dreaming about getting married with her' },
	{ status: 'OK', msg: 'having 11 Babyes' },
	{ status: 'OK', msg: 'She looked at me ' },
	{ status: 'OK', msg: 'i smilled' },
	{ status: 'OK', msg: 'she smilled' },
	{ status: 'OK', msg: 'went to ask her number ' },
	{ status: 'Failed', msg: 'she said i looked like her brother' }
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' },
	// { status: '', msg: '' }
];
export default data;
